// import { useRouter } from 'next/navigation';
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";
import i from "./favicon.ico";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Asset Tracking",
    description: "Generated by create next app",
    icons:{
        icon:"/favicon.svg",
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // useEffect(() => {
    //     setPath(router.pathname);
    // }, [router.pathname]);

    return (
        <>
            <html lang="en">
                <body className={inter.className}>
                    <NavBar />
                    {children}
                </body>
            </html>
        </>
    );
}
